stages:
  - test
  - build

default:
  image: buildkite/puppeteer:latest

  cache:
    key: global-cache
    paths:
      - node_modules/

  before_script:
    - npm install

unit tests:
  stage: test
  script:
    - apt-get update && apt-get -y install procps
    - npm run test --ci

pages:
  image: node:stretch-slim
  stage: build
  script:
    - npm install
    - npm run build
    - cp examples/index.html public/
  artifacts:
    paths:
      - public
  only:
    - master
