stages:
  - test
  - build
  - docs
  - deploy

default:
  image: altwalker/tests:model-visualizer
  cache:
    key: global-
    paths:
      - node_modules/

chromium tests:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test --ci

firefox tests:
  stage: test
  artifacts:
    paths:
      - screenshots/
    when: always
  variables:
    PUPPETEER_BROWSER: firefox
  before_script:
    - npm install
  script:
    - npm run test --ci

build:
  image: node:stretch-slim
  stage: build
  only:
    - master
  artifacts:
    paths:
      - build
  before_script:
    - npm install
  script:
    - npm run build
  after_script:
    - cp -r public build

docs:
  image: python:3.8
  stage: docs
  only:
    - master
  artifacts:
    paths:
      - documentation
  before_script:
    - curl -sL https://deb.nodesource.com/setup_13.x | bash -
    - apt-get install -y nodejs
    - npm install -g jsdoc
    - pip install -r requirements.txt
  script:
    - cd docs
    - make html
    - ls -alt _build/html
    - cp -r _build/html ../documentation
    
pages:
  image: alpine:3.7
  stage: deploy
  only:
    - master
  dependencies:
    - build
    - docs
  artifacts:
    paths:
      - public
  script:
    - cp -r documentation/ public/
    - cp -r build/ public/build/
