name: Unit Tests & Integration Tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test.yml'

env:
  NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install npm dependencies
      run: |
        npm install

    - name: Lint with eslint
      run: |
        npm run lint

  tests:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        browser: [chromium]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install npm dependencies
      run: |
        npm install

    - name: Run tests
      env:
        PUPPETEER_BROWSER: ${{ matrix.browser }}
      run: |
        npm run test --ci

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: screenshots-${{ matrix.browser }}
        path: 'screenshots/'

  build:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install npm dependencies
      run: |
        npm install

    - name: Build
      run: |
        npm run build

    - name: Upload build
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: build
        path: 'public/'
